### ISSUE TITLE
Question : Barcode position

### ISSUE THREAD

**Issue by tleluc** [mkoppanen/php-zbarcode#12]
Hi mkoppanen,

Is there a way to get barcodes position and bounding box with the php-zbarcode PHP Extension ?

**Comment by hansallis** [comment]
Absolutely. Just pass true as the third parameter to retrieve extended information. The second parameter defaults to 1 and indicates the page number. Example output:

`array(1) {
  [0]=>
  array(4) {
    ["data"]=>
    string(6) "746120"
    ["type"]=>
    string(4) "I2/5"
    ["quality"]=>
    int(1)
    ["location"]=>
    array(1) {
      [0]=>
      array(2) {
        ["x"]=>
        int(368)
        ["y"]=>
        int(1021)
      }
    }
  }
}`
